### ISSUE TITLE
Make Development environment of Project

### ISSUE THREAD

**Issue by seo2im** [sparta42/Client-react#14]
## Description
make development environment of Project

### Todo
- [x] set ESlint(code convention in code)
- [x] set package version
- [x] set code review in github
- [x] set github workflow

**Comment by seo2im** [comment]
### lint setting
1. d8fdbaaae592124e12ac43cec9304249b3b72fef

### git env setting:
1. c1c8ff86f0333bf7c22ff82faf76cf9a644634ac (workflow 등록, template 등록)
2. 7bc47b099ff856ec8a4358b6c5122deb24f8dc3b (yml 오류 수정)
3. 60c32bcdee9b41f5bd0974ef65b8a5d2846d0538 (기존 push test 규정 변경)
