### ISSUE TITLE
Connect naver static map Api [dokang]

### ISSUE THREAD

**Issue by 107dongu** [sparta42/Client-react#16]
## Description
 Connect naver static map api
### Todo
- [ ] create image tag in body
- [ ] make map option object
- [ ] set src attribute in image tag using map option object
