### ISSUE TITLE
Make Map layer sample

### ISSUE THREAD

**Issue by seo2im** [sparta42/Client-react#19]
## Description
make map layer sample

### Todo
- [ ] connect naver map api
- [ ] set static map
- [ ] set geoloaction API
- [ ] set calculate of gis
- [ ] dragable event setting
