### ISSUE TITLE
Make Map layer Sample

### ISSUE THREAD

**Issue by Kkan9ma** [sparta42/Client-react#21]
### Todo
- [ ] Connect naver map api
- [ ] Display static map
- [ ] Implement `getcurrentposition feature`
- [ ] Some events(on the map)
